# -*- coding: utf-8 -*-
"""Data Scraping and Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkM6wMNaFQIfOvyb7kZr2-fGUalS05EZ

# Use Case: ITC Financial Analysis with AI Scraping & LLM Integration

## Objective
Analyze **ITC Limited**'s revenue trends, profitability, and overall financial health by leveraging **AI-based web scraping** and **LLM-driven insights**.

## Installing The Required Librires
"""

!pip install tavily-python

"""## Importing Reuired Librires

"""

import os
from tavily import TavilyClient
from langchain.schema import Document

from google.colab import userdata
tv_api=userdata.get('tv')

"""### Extracting Financial Documents from ITC Website using tavily

#### 1.Annual Reports for ITC - 2023 and 2024
"""

# Annual Reports for ITC - 2023 and 2024

client = TavilyClient(tv_api)

pdf_sources_annual = [
    {
        "url": "https://www.itcportal.com/about-itc/shareholder-value/annual-reports/itc-annual-report-2023/pdf/ITC-Report-and-Accounts-2023.pdf",
        "metadata": {"source": "ITC Report and Accounts 2023"}
    },
    {
        "url": "https://www.itcportal.com/about-itc/shareholder-value/annual-reports/itc-annual-report-2024/pdf/ITC-Report-and-Accounts-2024.pdf",
        "metadata": {"source": "ITC Report and Accounts 2024"}
    },
]

"""#### 2. Quarterly Reports for FY2023"""

# Quarterly Reports for FY2023
pdf_sources_qtr_fy2023 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q1-FY2023.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q1 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q2-FY2023.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q2 FY2023"}
    },
    # {
    #     "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q3-FY2023.pdf",
    #     "metadata": {"source": "Quarterly Result Presentation Q3 FY2023"}
    # },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q4-FY2023.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q4 FY2023"}
    },
]

"""#### 3.Quarterly Reports for FY2024"""

# Quarterly Reports for FY2024
pdf_sources_qtr_fy2024 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q1-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q1 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q2-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q2 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q3-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q3 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q4-FY2024.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q4 FY2024"}
    },
]

"""#### 4. Quarterly Reports for FY2025"""

# Quarterly Reports for FY2025
pdf_sources_qtr_fy2025 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q1-FY2025.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q1 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q2-FY2025.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q2 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Quarterly-Result-Presentation-Q3-FY2025.pdf",
        "metadata": {"source": "Quarterly Result Presentation Q3 FY2025"}
    },
]

"""#### 5. Standalone Financial Reports for FY2023"""

# Standalone Financial Reports for FY2023
pdf_sources_financial_fy2023 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q1 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q2 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q3 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2023-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q4 FY2023"}
    },
]

"""#### 6. Standalone Financial Reports for FY2024"""

# Standalone Financial Reports for FY2024
pdf_sources_financial_fy2024 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q1 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q2 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q3 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2024-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q4 FY2024"}
    },
]

"""#### 7. Standalone Financial Reports for FY2025"""

# Standalone Financial Reports for FY2025
pdf_sources_financial_fy2025 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2025-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q1 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2025-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q2 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2025-sfs.pdf",
        "metadata": {"source": "Standalone Financial Result Q3 FY2025"}
    },
]

"""8.Consolidated Financial Reports for FY2023"""

pdf_sources_cs_fy2023 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q1 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q2 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q3 FY2023"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2023-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q4 FY2023"}
    },
]

"""9.Consolidated Financial Reports for FY2024"""

pdf_sources_cs_fy2024 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q1 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q2 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q3 FY2024"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q4-FY2024-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q4 FY2024"}
    },
]

"""Consolidated Financial Reports for FY2025"""

pdf_sources_cs_fy2025 = [
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q1-FY2025-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q1 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q2-FY2025-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q2 FY2025"}
    },
    {
        "url": "https://www.itcportal.com/investor/pdf/ITC-Financial-Result-Q3-FY2025-cfs.pdf",
        "metadata": {"source": "Consolidated Financial Result Q3 FY2025"}
    },
]

"""#### Extracting and Creating Documents"""

# Looping through all PDFs, extract content, and create Document objects
documents = []
for pdf in pdf_sources_annual + pdf_sources_qtr_fy2023 + pdf_sources_qtr_fy2024 + pdf_sources_qtr_fy2025 + pdf_sources_financial_fy2024 + pdf_sources_financial_fy2025 + pdf_sources_cs_fy2023 + pdf_sources_cs_fy2024 + pdf_sources_cs_fy2025:
    response = client.extract(urls=[pdf["url"]], extract_depth="advanced")
    # Check if results were extracted
    if response and response["results"]:
        content = response["results"][0]["raw_content"]
        documents.append(Document(page_content=content, metadata=pdf["metadata"]))
    else:
        print(f"Extraction failed for URL: {pdf['url']}")

documents[4]

del documents[4]

documents[4]

"""#### Cleaning the Documents"""

import re

def cleaning(text):

    # Lower
    text = text.lower()

    # Remove HTML tags
    text = re.sub(r'<[^>]+>', ' ', text)

    # Remove URLs (http, https, www)
    text = re.sub(r'http\S+|www\.\S+', ' ', text)

    # Remove Markdown links: [text](link)
    text = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', text)

    # Remove HTML links: <a href="...">text</a> (already removed by HTML tag regex, but just in case)
    text = re.sub(r'<a\s+(?:[^>]*?\s+)?href="[^"]*">(.*?)</a>', r'\1', text)

    return text

for doc in documents:
   doc.page_content = cleaning(doc.page_content)

documents[2]

for doc in documents:
    print(doc.metadata.keys())
    print(doc.metadata.values())


source = documents[0].metadata['source']
print(source)

"""#### Pickleing the documents"""

import pickle

with open("documents2.pkl", "wb") as f:
    pickle.dump(documents, f)



